module.exports = {
    ABOUT_US_BANNER_IMAGE_SUCCESS: "ABOUT_US_BANNER_IMAGE_SUCCESS",
    ABOUT_US_BANNER_IMAGE_FAILURE: "ABOUT_US_BANNER_IMAGE_FAILURE",
    PRODUCT_BANNER_IMAGE_SUCCESS: "PRODUCT_BANNER_IMAGE_SUCCESS",
    PRODUCT_BANNER_IMAGE_FAILURE: "PRODUCT_BANNER_IMAGE_FAILURE"
}