module.exports = {
    GET_BANNER_IMAGE_SUCCESS: "GET_BANNER_IMAGE_SUCCESS",
    GET_BANNER_IMAGE_FAILED: "GET_BANNER_IMAGE_FAILED",
    GET_BIKE_VARIANTS_SUCCESS: "GET_BIKE_VARIANTS_SUCCESS",
    GET_BIKE_VARIANTS_FAILED: "GET_BIKE_VARIANTS_FAILED",
    GET_TESTIMONIAL_LIST_SUCCESS: "GET_TESTIMONIAL_LIST_SUCCESS",
    GET_TESTIMONIAL_LIST_FAILED: "GET_TESTIMONIAL_LIST_FAILED",
    GET_PARTNERS_LIST_SUCCESS: "GET_PARTNERS_LIST_SUCCESS",
    GET_PARTNERS_LIST_FAILED: "GET_PARTNERS_LIST_FAILED",
}